Parameters:
  domainname:
    Type: String
    Default: static.example.com
    Description: Domain Name
Resources:
  s3bucket1F310132:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName:
        Ref: domainname
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            ExpiredObjectDeleteMarker: true
            Id: multipart
            Status: Enabled
          - Id: IA
            Status: Enabled
            Transitions:
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 0
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Domain
          Value:
            Ref: domainname
        - Key: Project
          Value: Wagtail Images
        - Key: stackName
          Value: S3CloudfrontStack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  s3bucketPolicy694C03A8:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: s3bucket1F310132
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListBucketVersions
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - User00B015A1
                  - Arn
            Resource:
              Fn::GetAtt:
                - s3bucket1F310132
                - Arn
            Sid: AllowUserManageBucket
          - Action: s3:*Object
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - User00B015A1
                  - Arn
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - s3bucket1F310132
                      - Arn
                  - /*
            Sid: AllowUserManageBucketObjects
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - CloudFrontDistributionOrigin1S3Origin3D9CA0E9
                  - S3CanonicalUserId
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - s3bucket1F310132
                      - Arn
                  - /*
          - Action:
              - s3:GetObject
              - s3:ListBucket
            Condition:
              StringEquals:
                aws:SourceArn:
                  Fn::Join:
                    - ""
                    - - "arn:aws:cloudfront::"
                      - Ref: AWS::AccountId
                      - :distribution/
                      - Ref: CloudFrontDistributionBA64CE3A
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource:
              - Fn::GetAtt:
                  - s3bucket1F310132
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - s3bucket1F310132
                        - Arn
                    - /*
        Version: "2012-10-17"
  User00B015A1:
    Type: AWS::IAM::User
    Properties:
      Tags:
        - Key: Domain
          Value:
            Ref: domainname
        - Key: Project
          Value: Wagtail Images
        - Key: stackName
          Value: S3CloudfrontStack
  AccessKeyE6B25659:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: User00B015A1
  SecretA720EF05:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString:
        Fn::GetAtt:
          - AccessKeyE6B25659
          - SecretAccessKey
      Tags:
        - Key: Domain
          Value:
            Ref: domainname
        - Key: Project
          Value: Wagtail Images
        - Key: stackName
          Value: S3CloudfrontStack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  myPolicyE3C880F7:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - iam:CreateAccessKey
              - iam:DeleteAccessKey
              - iam:ListAccessKeys
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - User00B015A1
                - Arn
        Version: "2012-10-17"
      PolicyName: myPolicyE3C880F7
      Users:
        - Ref: User00B015A1
  MyCertificate41357985:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        Ref: domainname
      Tags:
        - Key: Domain
          Value:
            Ref: domainname
        - Key: Name
          Value:
            Ref: domainname
        - Key: Project
          Value: Wagtail Images
        - Key: stackName
          Value: S3CloudfrontStack
      ValidationMethod: DNS
  MyCfnOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: CF S3 Origin Access Control
        Name:
          Ref: domainname
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  CloudFrontDistributionOrigin1S3Origin3D9CA0E9:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for S3CloudfrontStackCloudFrontDistributionOrigin1C0DF82F7
  CloudFrontDistributionBA64CE3A:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Ref: domainname
        CustomErrorResponses:
          - ErrorCachingMinTTL: 60
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          TargetOriginId: s3-static-frontend
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName:
              Fn::GetAtt:
                - s3bucket1F310132
                - RegionalDomainName
            Id: s3-static-frontend
            OriginAccessControlId:
              Fn::GetAtt:
                - MyCfnOriginAccessControl
                - Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Ref: MyCertificate41357985
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
      Tags:
        - Key: Domain
          Value:
            Ref: domainname
        - Key: Project
          Value: Wagtail Images
        - Key: stackName
          Value: S3CloudfrontStack
Outputs:
  userNAME:
    Value:
      Ref: User00B015A1
  accessKeyId:
    Value: S3CloudfrontStack/AccessKey
  SiteBucketName:
    Value:
      Ref: s3bucket1F310132
  DistributionId:
    Value:
      Ref: CloudFrontDistributionBA64CE3A
  distributionDomainName:
    Value:
      Fn::GetAtt:
        - CloudFrontDistributionBA64CE3A
        - DomainName
  CertificateArn:
    Value:
      Ref: MyCertificate41357985

